// vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - tanstackStart, viteReact, tailwindcss, tsConfigPaths, nitro (build-only),
//     componentTagger (dev-only), VITE_* env injection, @ path alias, React/TanStack dedupe,
//     error logger plugins, and sandbox detection (port/host/strictPort).
// You can pass additional config via defineConfig({ vite: { ... }, etc... }) if needed.
// This project force-enables Nitro with preset "vercel" for self-deploy.
import { readFileSync, writeFileSync } from "node:fs";

import type { Plugin } from "vite";
import { defineConfig } from "@lovable.dev/vite-tanstack-config";

import { getSecurityHeaders } from "./src/lib/security-headers";

const ROUTE_TREE_BANNER =
  /\/\/ This file was automatically generated by TanStack Router\.\r?\n\/\/ You should NOT make any changes in this file as it will be overwritten\.\r?\n\/\/ Additionally, you should also exclude this file from your linter and\/or formatter to prevent it from being checked or modified\./g;

const ROUTE_TREE_BANNER_SAFE =
  "// Auto-generated route tree — do not edit. Regenerated when routes change.";

function sanitizeRouteTreeComments(): Plugin {
  const rewrite = (file: string) => {
    if (!file.replace(/\\/g, "/").endsWith("routeTree.gen.ts")) return;
    try {
      const current = readFileSync(file, "utf8");
      const next = current.replace(ROUTE_TREE_BANNER, ROUTE_TREE_BANNER_SAFE);
      if (next !== current) writeFileSync(file, next, "utf8");
    } catch {
      // File may be mid-write during generation.
    }
  };

  return {
    name: "sanitize-route-tree-comments",
    transform(code, id) {
      if (!id.includes("routeTree.gen")) return null;
      return code.replace(ROUTE_TREE_BANNER, ROUTE_TREE_BANNER_SAFE);
    },
    configureServer(server) {
      server.watcher.on("add", rewrite);
      server.watcher.on("change", rewrite);
    },
  };
}

function securityHeadersPlugin(): Plugin {
  const applyHeaders = (
    req: { headers?: { host?: string } },
    res: { setHeader: (name: string, value: string) => void },
    next: () => void,
  ) => {
    const hostHeader = req.headers?.host ?? "";
    const [hostname, port] = hostHeader.split(":");
    // Nonce-based CSP is applied by TanStack Start middleware — do not set CSP here
    // or it will lack the matching script nonce and break the page.
    const headers = getSecurityHeaders({
      hostname: hostname || undefined,
      port: port || undefined,
    });
    for (const [name, value] of Object.entries(headers)) {
      if (name === "Content-Security-Policy") continue;
      res.setHeader(name, value);
    }
    next();
  };

  return {
    name: "risk-sentinel-security-headers",
    configureServer(server) {
      server.middlewares.use(applyHeaders);
    },
    configurePreviewServer(server) {
      server.middlewares.use(applyHeaders);
    },
  };
}

export default defineConfig({
  // Force Nitro outside Lovable so `vite build` produces a Vercel-ready deploy artifact.
  // Pin vercel (do not rely on Cloudflare defaultPreset from the Lovable helper).
  nitro: {
    preset: process.env.NETLIFY ? "netlify" : process.env.VERCEL ? "vercel" : (process.env.NITRO_PRESET || "vercel"),
  },
  tanstackStart: {
    // Redirect TanStack Start's bundled server entry to src/server.ts (our SSR error wrapper).
    // nitro/vite builds from this
    server: { entry: "server" },
    // Colocated Vitest files under src/routes/*.test.tsx are not routes — ignore them
    // so the router stops flooding the terminal and hiding the Local/Network URLs.
    router: {
      routeFileIgnorePattern: "\\.test\\.(ts|tsx)$",
      // Keep generated header free of ZAP "suspicious comment" tokens (e.g. FROM).
      routeTreeFileHeader: [
        "/* eslint-disable */",
        "// @ts-nocheck",
        "// noinspection JSUnusedGlobalSymbols",
        "// Auto-generated by TanStack Router — do not edit.",
        "// Keep this file out of lint/format pipelines; regeneration overwrites it.",
      ],
    },
  },
  vite: {
    plugins: [sanitizeRouteTreeComments(), securityHeadersPlugin()],
    server: {
      host: true, // bind 0.0.0.0 / all interfaces
      port: 8080,
      strictPort: false, // fall back if 8080 busy (was used after port conflict issues)
      // Allow phone/LAN hostnames (e.g. 172.x) so login server functions work off localhost.
      allowedHosts: true,
    },
  },
});
